spring:
  main:
    allow-bean-definition-overriding: true  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
  datasource:
    claimstore:
      driverClassName: org.postgresql.Driver
      username: ${CLAIM_STORE_DB_USERNAME:-}
      password: ${CLAIM_STORE_DB_PASSWORD:-}
      url: jdbc:postgresql://${CLAIM_STORE_DB_HOST:}:${CLAIM_STORE_DB_PORT:}/${CLAIM_STORE_DB_NAME:claimstore}${CLAIM_STORE_DB_CONNECTION_OPTIONS:}
claimstore:
  api:
    url: http://localhost:4400
