server:
  port: 4400

management:
  security:
    enabled: false

database:
  driverClassName: org.postgresql.Driver
  username: ${CLAIM_STORE_DB_USERNAME:-}
  password: ${CLAIM_STORE_DB_PASSWORD:-}
  url: jdbc:postgresql://${CLAIM_STORE_DB_HOST:-}:${CLAIM_STORE_DB_PORT:-}/claimstore${CLAIM_STORE_DB_CONNECTION_OPTIONS:}
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1
  minSize: 8
  maxSize: 32
  evictionInterval: 10
  minIdleTime: 1 minute
  checkConnectionWhileIdle: true
  checkConnectionOnReturn: true
  removeAbandoned: true
  removeAbandonedTimeout: 60
  abandonWhenPercentageFull: 0
  testOnBorrow: true
  validationQuery: SELECT 1

spring:
  mail:
    default-encoding: UTF-8
    test-connection: true

idam:
  api:
    url: "http://localhost:8080"

bankHolidays:
  api:
    url: "https://www.gov.uk"

dateCalculations:
  endOfBusinessDayHour: 16
  serviceDays: 4
  responseDays: 14
  requestedAdditionalTimeInDays: 14
  freeMediationTimeForDecisionInDays: 28

notifications:
  govNotifyApiKey: ${GOV_NOTIFY_API_KEY:}
  frontendBaseUrl: "${FRONTEND_BASE_URL:}"
  templates:
    email:
      claimantClaimIssued: "d7bbde3d-4c74-41f0-a4d4-4df2c53b1310"
      defendantClaimIssued: "dac659a6-2893-4205-81fb-1d42f47ccb13"
      defendantResponseIssued: "e8636e5e-17d8-4390-81fb-23235f2d1fbf"
      claimantResponseIssued: "cf444aa0-d578-4d03-b680-baaf08512016"
      staffMoreTimeRequested: "b0a060d2-62be-405a-9f74-0377fdaaed28"
      claimantMoreTimeRequested: "cfe5bb37-6f17-40c8-b14e-18b4fcfb9125"
      defendantMoreTimeRequested: "03b4dc3d-2768-4aa5-9e29-2e537149254f"
      representativeClaimIssued: "f2b21b9c-fc4a-4589-807b-3156dbf5bf01"

staff-notifications:
  sender:
  recipient:

pdfService:
  baseUrl: ${PDF_SERVICE_URL:}

---
spring:
  profiles: test

claim-store:
  test-support:
    enabled: true
