dependencies:
  - name: java
    version: ~2.2.2
    repository: '@hmctspublic'
  - name: postgresql
    version: ~2.6.5
    repository: '@stable'
    tags:
      - cmc-claim-store-postgresql-pod
  - name: cmc-citizen-frontend
    version: ~1.0.8
    repository: '@hmctspublic'
    tags:
      - cmc-citizen-frontend-pod
  - name: ccd
    version: ~4.0.0
    #repository: '@hmctspublic'
    repository: '/Users/kariml/Development/chart-ccd/ccd'
    tags:
      - cmc-ccd-stack
