java:
  ingressHost: cmc-claim-store.service.core-compute-aat.internal
  keyVaults:
    cmc:
      resourceGroup: cmc
      secrets:
        - claim-store-db-password
        - cmc-db-password
        - AppInsightsInstrumentationKey
        - citizen-oauth-client-secret
        - claim-store-s2s-secret
        - anonymous-caseworker-username
        - anonymous-caseworker-password
        - system-update-username
        - system-update-password
        - notify-api-key
  environment:
    CORE_CASE_DATA_API_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    SEND_LETTER_URL: http://rpe-send-letter-service-aat.service.core-compute-aat.internal
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    PDF_SERVICE_URL: http://cmc-pdf-service-aat.service.core-compute-aat.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-aat.service.core-compute-aat.internal
    DOC_ASSEMBLY_URL: false
    FRONTEND_BASE_URL: https://cmc-citizen-frontend.service.core-compute-aat.internal
    RESPOND_TO_CLAIM_URL: https://cmc-citizen-frontend.service.core-compute-aat.internal/first-contact/start
    CLAIM_STORE_DB_HOST: preprod-data-lb.moneyclaim.reform.hmcts.net
    CLAIM_STORE_DB_CONNECTION_OPTIONS: '?sslmode=require'
    CMC_DB_HOST: cmc-aat.postgres.database.azure.com
    CMC_DB_USERNAME: 'cmc@cmc-aat'
    CMC_DB_CONNECTION_OPTIONS: '?sslmode=require'
    FEATURE_TOGGLES_CCD_ENABLED: true
    FEATURE_TOGGLES_CCD_ASYNC_ENABLED: false
    FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
    FEATURE_TOGGLES_ASYNC_EVENT_OPERATIONS_ENABLED: true
    FEATURE_TOGGLES_EMAILTOSTAFF: true
    FEATURE_TOGGLES_DIRECTIONS_QUESTIONNAIRE_ENABLED: false
